#ifndef TYPECOMP_H
#define TYPECOMP_H

enum class TypeComp {
    MATERIAL, TRANSFORM, TEXTURE, CAMERA, SKYBOX
};

enum class CompLigth {
    AMBIENT, DIFFUSE, SPECULAR, SCENE, DIRECTIONAL, POINT, SPOT
};

#endif // TYPECOMP_H
